# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- main


stages:
  - stage: oci terraform
    jobs:
      - job: validate
        continueOnError: false
        steps:
        - task: TerraformInstaller@1
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'

        - script: |
            echo Execute Terraform script.
          displayName: 'Runing Terraform script'

        - script: |
            ./Initialize-Terraform.ps1 -Workspace $(TFWorkspace) -Application $(TFApplication) -Type $(TFType)
          displayName: "Initializing Terraform for $(TFWorkspace)"
